name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@c06fa48ce59e016105d79c20942d085314502d8d
